/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Media.gltf --transform 
Files: Media.gltf [569.17KB] > C:\Users\Administrator\Desktop\New folder (7)\New folder (5)\Media-transformed.glb [470.56KB] (17%)
Author: brian-aa (https://sketchfab.com/brian-aa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/some-cubes-5fabac1213db4ca29ba2a4871249db25
Title: SoMe Cubes
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Media-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="soMe_Cubes_low_GRP" scale={0.01}>
          <group name="cube_Instagram_GEO" position={[-12, 0, 0]}>
            <mesh name="cube_Instagram_GEO_C_soMe_MAT_0" geometry={nodes.cube_Instagram_GEO_C_soMe_MAT_0.geometry} material={materials.C_soMe_MAT} />
          </group>
          <group name="cube_Facebook_GEO" position={[-4, 0, 0]}>
            <mesh name="cube_Facebook_GEO_C_soMe_MAT_0" geometry={nodes.cube_Facebook_GEO_C_soMe_MAT_0.geometry} material={materials.C_soMe_MAT} />
          </group>
          <group name="cube_Twitter_GEO" position={[4, -0.008, 0]}>
            <mesh name="cube_Twitter_GEO_C_soMe_MAT_0" geometry={nodes.cube_Twitter_GEO_C_soMe_MAT_0.geometry} material={materials.C_soMe_MAT} />
          </group>
          <group name="cube_Youtube_GEO" position={[12, 0, 0]}>
            <mesh name="cube_Youtube_GEO_C_soMe_MAT_0" geometry={nodes.cube_Youtube_GEO_C_soMe_MAT_0.geometry} material={materials.C_soMe_MAT} />
          </group>
          <group name="cube_Reddit_GEO" position={[-12, 8, 0]}>
            <mesh name="cube_Reddit_GEO_C_soMe_MAT_0" geometry={nodes.cube_Reddit_GEO_C_soMe_MAT_0.geometry} material={materials.C_soMe_MAT} />
          </group>
          <group name="cube_Whatsapp_GEO" position={[-4, 8, 0]}>
            <mesh name="cube_Whatsapp_GEO_C_soMe_MAT_0" geometry={nodes.cube_Whatsapp_GEO_C_soMe_MAT_0.geometry} material={materials.C_soMe_MAT} />
          </group>
          <group name="cube_Pinterest_GEO" position={[4, 8, 0]}>
            <mesh name="cube_Pinterest_GEO_C_soMe_MAT_0" geometry={nodes.cube_Pinterest_GEO_C_soMe_MAT_0.geometry} material={materials.C_soMe_MAT} />
          </group>
          <group name="cube_LinkedIn_GEO" position={[12, 8, 0]}>
            <mesh name="cube_LinkedIn_GEO_C_soMe_MAT_0" geometry={nodes.cube_LinkedIn_GEO_C_soMe_MAT_0.geometry} material={materials.C_soMe_MAT} />
          </group>
          <group name="cube_TikTok_GEO" position={[-12, 16, 0]}>
            <mesh name="cube_TikTok_GEO_C_soMe_MAT_0" geometry={nodes.cube_TikTok_GEO_C_soMe_MAT_0.geometry} material={materials.C_soMe_MAT} />
          </group>
          <group name="cube_Twitch_GEO" position={[-4, 16, 0]}>
            <mesh name="cube_Twitch_GEO_C_soMe_MAT_0" geometry={nodes.cube_Twitch_GEO_C_soMe_MAT_0.geometry} material={materials.C_soMe_MAT} />
          </group>
          <group name="cube_Snapchat_GEO" position={[4, 16, 0]}>
            <mesh name="cube_Snapchat_GEO_C_soMe_MAT_0" geometry={nodes.cube_Snapchat_GEO_C_soMe_MAT_0.geometry} material={materials.C_soMe_MAT} />
          </group>
          <group name="cube_Threads_GEO" position={[12, 16, 0]}>
            <mesh name="cube_Threads_GEO_C_soMe_MAT_0" geometry={nodes.cube_Threads_GEO_C_soMe_MAT_0.geometry} material={materials.C_soMe_MAT} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Media-transformed.glb')
